### ISSUE TITLE
Publish for ROS 2 foxy + galactic

### ISSUE THREAD

**Issue by amacneil** [foxglove/ros_foxglove_msgs#2]
I believe this package is currently available in ROS 1 (noetic). We should add it to ROS 2 (foxy + galactic) distros as well.

**Comment by yukke42** [comment]
Hello. We updated this package for ros2 (galactic) .
I hope it helps you.
https://github.com/tier4/ros_foxglove_msgs

**Comment by amacneil** [comment]
@yukke42 thanks!
