### ISSUE TITLE
Release 1.1.0

### ISSUE THREAD

**Issue by jhurliman** [foxglove/ros_foxglove_msgs#4]
Need to update the changelog (only change from 1.0.0 is adding ROS2 support) and create a tag.

**Comment by jhurliman** [comment]
It looks like we have a CMake warning to fix first: https://build.ros.org/job/Ndev__foxglove_msgs__ubuntu_focal_amd64/2/

```
Policy CMP0048 is not set: project() command manages VERSION variables.
```

@wep21 can you take a look at this?

**Comment by wep21** [comment]
@jhurliman Thank you for letting me know. I will fix it.
